Repository pauwels-labs/redact-crypto, pull requests merged in 2021-09, with the labels that each got.

#5 feat: add x509 support
  Cargo.lock
  Cargo.toml
  src/data.rs
  src/key.rs
  src/key/ring.rs
  src/key/sodiumoxide.rs
  src/lib.rs
  src/x509.rs
Labels: approved, size/XL

#6 Google cloud storage
  Cargo.lock
  Cargo.toml
  src/entry.rs
  src/error.rs
  src/storage.rs
  src/storage/gcs.rs
  src/storage/mongodb.rs
  src/storage/redact.rs
Labels: size/XXL, approved

#8 Separate indexed storer
  Cargo.lock
  Cargo.toml
  src/entry.rs
  src/error.rs
  src/key/sodiumoxide.rs
  src/lib.rs
  src/storage.rs
  src/storage/gcs.rs
  src/storage/mongodb.rs
  src/storage/redact.rs
Labels: approved, size/L

#12 Implement Verifier for all Signing Keys
  src/entry.rs
  src/error.rs
  src/key.rs
  src/key/ring.rs
  src/key/sodiumoxide.rs
Labels: approved, size/L

#10 feat: add support for TLS auth on Redact storer
  Cargo.lock
  Cargo.toml
  src/entry.rs
  src/storage/redact.rs
Labels: approved, size/L
